### ISSUE TITLE
how to deal with data unbalance?

### ISSUE THREAD

**Issue by boozyguo** [rdcolema/nc-fish-classification#2]
In fish classification, some fishes are more less than 'ALB'. 
I have try to using "class_weights" parameters in fit function, but the results have not been improved.
So, how to deal with the unbalance data?
Thanks a lot.

**Comment by rdcolema** [comment]
Hi Meng,

There are a few ways to try to combat class imbalance -- one is with weighted classes, which you mentioned you tried already. Another is using data augmentation to generate new, slightly altered examples of images that belong to underrepresented classes (which I tried early on in this competition). A third strategy is just finding more data, but that's probably not much of an option for this dataset. 

However, I'll note that I haven't seen any gains in performance from using the above techniques in the context of this particular project, and in general I think CNNs are pretty robust against class imbalance.  I also haven't heard of any of the top performers in this Kaggle competition taking measures against class imbalance yet, but could be wrong there.
